spring:
  application:
    name: smart-hire
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:smarthire}
    username: ${DB_USER:smarthire}
    password: ${DB_PASSWORD:smarthire123}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:HieurmchsHellosusaafjRepodjgOrangesjgvnfkrslsas}