spring:
  config:
    import: "optional:file:../.env[.properties]"
  application:
    name: smart-hire
  datasource:
      url: jdbc:postgresql://localhost:5432/smartHire
      username: postgres
      password: Blaze2326@
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:X7v3k9Qp2N8mZ6wJ4tR1yB5cV0sD3fH8gK7lM2nO9pQ6rT4uW1xY5zA3bC0eG7hJ}
