export enum NotificationType {
    APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
    APPLICATION_STAGE_CHANGED = 'APPLICATION_STAGE_CHANGED',
    INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
    INTERVIEW_UPDATED = 'INTERVIEW_UPDATED',
    JOB_POSTING_CREATED = 'JOB_POSTING_CREATED',
    SYSTEM = 'SYSTEM'
}