export enum NotificationType {
    APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
    APPLICATION_STAGE_CHANGED = 'APPLICATION_STAGE_CHANGED',
    INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
    FEEDBACK_SUBMITTED = 'FEEDBACK_SUBMITTED',
    SYSTEM = 'SYSTEM'
}